apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-hello
  labels:
    app: php-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-hello
  template:
    metadata:
      labels:
        app: php-hello
    spec:
      containers:
      - name: php-hello
        image: xmb233/argocd-php-hello:release-6
        ports:
        - containerPort: 80
